---
apiVersion: v1
kind: Namespace
metadata:
  name: rmapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rmapp
  name: rmapp
  namespace: rmapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmapp
  template:
    metadata:
      labels:
        app: rmapp
    spec:
      containers:
      - image: jogaleins/rmapp:<TAG>
        imagePullPolicy: Always
        name: rmapp

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rmapp
  name: rmapp
  namespace: rmapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: rmapp
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: rmapp-ing
  namespace: rmapp
  annotations:
    kubernetes.io/ingress.class: traefik
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: cloud.adrianpazon.com
    http:
      paths:
      - backend:
          service:
            name: rmapp
            port:
              number: 80
        path: /rmapp
        pathType: Exact
status:
  loadBalancer: {}